### ISSUE TITLE
Assistance with patch 

### ISSUE THREAD

**Issue by Shaggythecat** [WonderfulParty/WonderfulPartyEnglish#1]
Hi! I just came across your project and was wondering if you would like any assistance with this? I don't see any contact info here, hence opening an issue.

I cannot help with translation, but I can help with other things such as: Mapping and implementation of any edited assets/menus, compiling a proper patch archive (instead of redistributing motion and scenario), and porting all work to the PC version of the game, and several other things.

I'm fairly familiar with Kaledio ADV Workshop games.

**Comment by WonderfulParty** [comment]
Hello, sorry for the very late reply.

Any help is welcome as I cannot do much other than translate the scenario. A real patch or a PC port would be a phenomenal improvement that I would greatly appreciate.

I am hudquy on Discord, if you're still interested. Thank you!
